name: Proxy Aggregator and Checker

on:
  schedule:
    - cron: '0 */2 * * *' # Автозапуск каждые 6 часов
  workflow_dispatch: # Возможность ручного запуска

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: pip install requests

    - name: Install Sing-Box (Core Checker)
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        bash <(curl -fsSL sing-box.app)
        sudo apt-get install -y sing-box

    - name: Run Aggregator and Test Pings
      run: python run_checker.py

    - name: Push Working Proxies to Repository
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add merged_base64 only_working.txt
        git commit -m "Удалены нерабочие серверы" || exit 0
        git push
